services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Clickio\ClickioConsent\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  Clickio\ClickioConsent\Hooks\PageRenderer\ConsentCodeInjector:
    public: true